[testServer]
BROKER_HOST = 10.4.234.176
BROKER_PORT = 5672
USER = AuxTalks
PASSWORD = IT_490_PROJECT
VHOST = AuxTalks
EXCHANGE = AuxTalksExchange
QUEUE = AuxTalksQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

